### ISSUE TITLE
missing dependency? 

### ISSUE THREAD

**Issue by sanimalp** [jimeh/rubocopfmt.el#5]
I tried running this, version 0.30 installed from melpa-stable, and needed to 'gem install minitest-hooks' before my invocation of the directive would work on the buffer. 

I am not very well versed at where something like this would go, other than in the readme, though.

**Comment by jimeh** [comment]
That's pretty strange. The only requirement is the `rubocop` gem itself. The only thing this package does is execute the `rubocop` binary passing in the relevant file and some options.

Do you have an error output maybe from when it was failing? And did regular `rubocop` work from a terminal with the `--auto-complete` option while it was failing within emacs?

**Comment by sanimalp** [comment]
I should preface this by saying I am very new to Ruby, and this could be my own setup causing issues. I do have a stack trace from the execution failure.

```
/Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find minitest-hooks-1.5.0 in any of the sources (Bundler::GemNotFound)
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
	from /Users/<user>/.rvm/gems/ruby-2.3.7/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/<user>/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/<user>/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'

```

Unfortunately, I did not test running rubocop manually from the command line before all this occurred, but I did test it afterward and it worked fine. 

At any rate, it works for me now. Thank you for building this tool!

**Comment by jimeh** [comment]
Right, it looks like you just didn't have all dependencies for the project you were working on. And cause rubocopfmt.el defaults to trying to run rubocop via `bundle exec`, you then got a dependency error from bundler. Simply running `bundle install` should have resolved the issue :)

I still do need to figure out a better way to deal with bundler dependency errors though, it's on my todo list.

If you have any other issues, please feel free to ask :)

**Comment by sanimalp** [comment]
Gotcha! thanks very much for taking a look at this. Appreciate it!
