### ISSUE TITLE
Even when rubocop-daemon started - performance still very low

### ISSUE THREAD

**Issue by sandric** [jimeh/rubocopfmt.el#6]
Strangely, but I seems to be unable to make it work using rubocop-daemon, I was using it before - and in vscode it works very fast, and I clearly can see difference when daemon started vs when normal rubocop exec. invoked. But in emacs calling `rubocopfmt` - I still see big delay. Is there some specific command to call rubocop-daemon, or I have to set up some different executable (which is strange since vscode finding daemonized executable without a problem) ?

**Comment by sandric** [comment]
Sorry, local issue

**Comment by jimeh** [comment]
@sandric I apologize, the README doesn't really go into any detail at all about how to use `rubocop-daemon`. I'll try and address that soon.

Basically, you need to customize `rubocopfmt-rubocop-command` which defaults to `rubocop`, and set it to `rubocop-daemon`, or `rubocop-daemon-wrapper` if you're using the wrapper script they provide.
